/**
 * This class is generated by jOOQ
 */
package fr.mazerty.shika.ishi.dao.jooq;


import fr.mazerty.shika.ishi.dao.jooq.tables.TApplication;
import fr.mazerty.shika.ishi.dao.jooq.tables.TUser;
import fr.mazerty.shika.ishi.dao.jooq.tables.TUserApplication;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Torii extends SchemaImpl {

	private static final long serialVersionUID = 744985823;

	/**
	 * The reference instance of <code>torii</code>
	 */
	public static final Torii TORII = new Torii();

	/**
	 * No further instances allowed
	 */
	private Torii() {
		super("torii");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.S_USER_ID);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			TApplication.T_APPLICATION,
			TUser.T_USER,
			TUserApplication.T_USER_APPLICATION);
	}
}
